import { developments, eventData, pipeline, stakeholders, sources } from './data/index.js';
import { signals as rawSignals } from './data/signals.js';
import { cleanSignals, getLastSignalUpdate } from './data-cleaner.js';
const $=id=>document.getElementById(id),storageKey='atlas-local-state-v2',saved=JSON.parse(localStorage.getItem(storageKey)||'{}'),localOpportunities=saved.opportunities||[],localDevelopments=saved.developments||[],signals=cleanSignals(rawSignals),allDevelopments=()=>[...localDevelopments,...developments];
const allPipeline=()=>{const base=Object.fromEntries(Object.entries(pipeline).map(([k,v])=>[k,[...v]]));localOpportunities.forEach(o=>(base[o.stage]||=[]).push(o));return base};
function persist(){localStorage.setItem(storageKey,JSON.stringify({opportunities:localOpportunities,developments:localDevelopments}))}function escapeHtml(v=''){return String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderOverview(){const d=allDevelopments();if($('decisionGrid'))$('decisionGrid').innerHTML=[...d].sort((a,b)=>(parseInt(b.score)||0)-(parseInt(a.score)||0)).slice(0,3).map(x=>`<article class="decision-card"><div class="card-top"><span class="badge ${x.level||'signal'}">${escapeHtml(x.state||'SIGNAL')}</span><span class="score">${escapeHtml(x.score||'—')}</span></div><h3>${escapeHtml(x.title)}</h3><p>${escapeHtml(x.text)}</p><small class="decision-action">${escapeHtml(x.action||x.evidence||'Review signal')}</small></article>`).join('');if($('eventPreview'))$('eventPreview').innerHTML=eventData.slice(0,3).map(e=>`<article class="event-mini"><div class="date-box"><b>${escapeHtml(e.day)}</b><span>${escapeHtml(e.month)}</span></div><div class="event-mini-body"><strong>${escapeHtml(e.name)}</strong><small>${escapeHtml(e.priority)}</small><p>${escapeHtml(e.detail||'Energy-transition engagement opportunity')}</p></div></article>`).join('');renderThemePulse()}
function renderDevelopments(filter='all'){const d=allDevelopments(),f=d.filter(x=>{const t=`${x.topic||''} ${x.title||''} ${x.text||''} ${x.state||''}`.toLowerCase();if(filter==='verified')return /verified|evidence|source records/.test(t);if(filter==='needs-review')return /watch|review|require verification|needs review/.test(t);if(filter==='tenders')return /tender|procurement|prequalification|ao select/.test(t);if(filter==='policy')return /regulation|policy|consultation|framework|anre|law/.test(t);if(filter==='grid')return /grid|transmission|onee|substation|kv/.test(t);return true});if($('developmentList'))$('developmentList').innerHTML=f.map(x=>`<article class="development-row"><span class="topic">${escapeHtml(x.topic||'SIGNAL')}</span><div class="dev-content"><h4>${escapeHtml(x.title)}</h4><p>${escapeHtml(x.text)}</p><small>${escapeHtml(x.state||'')} ${x.action?`· ${escapeHtml(x.action)}`:''}</small></div><div class="dev-meta">${escapeHtml(x.published||x.date||'')}</div></article>`).join('')||'<div class="empty-state">No developments match this filter.</div>';document.querySelectorAll('.filter-row .filter').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter))}
function renderPipeline(){const b=allPipeline();if($('pipelineBoard'))$('pipelineBoard').innerHTML=Object.entries(b).map(([s,items])=>`<section class="pipe-column"><h3>${escapeHtml(s)}<span>${items.length}</span></h3>${items.map(i=>`<div class="pipe-item"><h4>${escapeHtml(i.name||i.title)}</h4><p>${escapeHtml(i.note||i.text||'')}</p><div class="pipe-meta"><span>${escapeHtml(i.owner||'Unassigned')}</span><span>${escapeHtml(i.due||'No due date')}</span></div></div>`).join('')}</section>`).join('')}
function renderEvents(){if($('eventList'))$('eventList').innerHTML=eventData.map(e=>`<article class="event-large"><div class="event-date"><b>${escapeHtml(e.day)}</b><span>${escapeHtml(e.month)}</span></div><div><h3>${escapeHtml(e.name)}</h3><p>${escapeHtml(e.detail)}</p><small class="event-priority">${escapeHtml(e.priority)}</small></div></article>`).join('')}
function renderThemePulse(){const d=allDevelopments(),b=[['Projects & tenders',/solar|pv|bess|storage|tender|project|construction/i],['Grid & policy',/grid|transmission|onee|anre|regulation|policy|tariff/i],['Hydrogen & PtX',/hydrogen|ammonia|ptx|power-to-x|electrolysis/i]],c=b.map(([,r])=>d.filter(x=>r.test(`${x.topic} ${x.title} ${x.text}`)).length),m=Math.max(1,...c),l=$('overview')?.querySelectorAll('.chart-labels span'),bars=$('overview')?.querySelectorAll('.bars i');c.forEach((n,i)=>{if(l?.[i])l[i].textContent=`${b[i][0]} · ${n}`;if(bars?.[i])bars[i].style.setProperty('--w',`${Math.max(12,Math.round(n/m*100))}%`)})}
function renderStatic(){if($('stakeholderGrid'))$('stakeholderGrid').innerHTML=stakeholders.map(s=>`<article><span class="org-type">${escapeHtml(s[1])}</span><h3>${escapeHtml(s[0])}</h3><p>${escapeHtml(s[2])}</p><small>${escapeHtml(s[3])} →</small></article>`).join('');if($('sourceRows'))$('sourceRows').innerHTML=sources.map(s=>`<div class="source-row"><span>${escapeHtml(s[0])}</span><span>${escapeHtml(s[1])}</span><span>${escapeHtml(s[2])}</span><span>${escapeHtml(s[3])}</span></div>`).join('')}
function renderCalendar(){const e=$('calendarDays');if(!e)return;const y=2026,m=8,f=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),o=(f.getDay()+6)%7;e.innerHTML=Array.from({length:o+days},(_,i)=>i<o?'<span></span>':`<button class="calendar-day">${i-o+1}</button>`).join('')}
function formatRefreshTime(value){if(!value)return 'Not available';const d=value instanceof Date?value:new Date(value);if(Number.isNaN(d.getTime()))return 'Not available';return d.toLocaleString('en-GB',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',timeZoneName:'short'});}
function renderSignalRefresh(){const last=getLastSignalUpdate(signals);window.atlasLastUpdate=last;const label=last?`Signals refreshed · ${formatRefreshTime(last)}`:'Signal refresh timestamp unavailable';let status=document.getElementById('atlasRefreshStatus');if(!status){status=document.createElement('div');status.id='atlasRefreshStatus';status.className='atlas-refresh-status';document.querySelector('.crumb')?.appendChild(status);}status.innerHTML=`<span class="atlas-refresh-dot"></span>${escapeHtml(label)}`;document.querySelectorAll('.view:not(#overview) .page-heading').forEach(h=>{let m=h.querySelector('.section-refresh-meta');if(!m){m=document.createElement('div');m.className='section-refresh-meta';h.appendChild(m);}m.innerHTML=`<span class="atlas-refresh-dot"></span>${escapeHtml(label)}`});}
function renderAll(){renderOverview();renderDevelopments(activeDevelopmentFilter);renderPipeline();renderEvents();renderStatic();renderCalendar();renderSignalRefresh()}function setView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav-item').forEach(v=>v.classList.toggle('active',v.dataset.view===id));renderSignalRefresh()}document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.querySelectorAll('[data-view-target]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.viewTarget)));
let activeDevelopmentFilter='all';const filterNames=['all','verified','needs-review','tenders','policy','grid'];document.querySelectorAll('.filter-row .filter').forEach((b,i)=>{b.dataset.filter=filterNames[i]||'all';b.addEventListener('click',()=>{activeDevelopmentFilter=b.dataset.filter;renderDevelopments(activeDevelopmentFilter)})});
function renderReportPreview(){const t=$('reportType')?.value||'Weekly Intelligence Brief',p=$('reportPeriod')?.value.trim()||'Current period',c=$('reportClassification')?.value||'';if($('reportPreview'))$('reportPreview').innerHTML=`<div class="report-cover"><span>ATLAS</span><p>MOROCCO RENEWABLE ENERGY INTELLIGENCE</p><h2>${escapeHtml(t)}</h2><small>${escapeHtml(p)} · ${escapeHtml(c)}</small></div>`}['reportType','reportPeriod','reportClassification'].forEach(id=>$(id)?.addEventListener('input',renderReportPreview));window.__atlasReportContextReady=true;window.allDevelopments=allDevelopments;window.allPipeline=allPipeline;window.eventData=eventData;window.signals=signals;window.atlasLastUpdate=getLastSignalUpdate(signals);window.escapeHtml=escapeHtml;renderAll();renderReportPreview();
import('./market-intelligence-v3.js?v=20260903-1').catch(e=>console.warn('Atlas market module unavailable',e));