import { developments, eventData, pipeline, stakeholders, sources } from './data/index.js';

function card(d) { return `<article class="decision-card"><div class="card-top"><span class="badge ${d.level}">${d.state}</span><span class="score">${d.score}</span></div><h3>${d.title}</h3><p>${d.text}</p><div class="card-foot"><span>${d.action}</span><span>${d.evidence}</span></div></article>`; }
document.getElementById('decisionGrid').innerHTML = developments.slice(0,3).map(card).join('');
document.getElementById('eventPreview').innerHTML = eventData.slice(0,2).map(e=>`<div class="event-mini"><div class="date-box"><b>${e.day}</b><span>${e.month}</span></div><div><strong>${e.name}</strong><small>${e.detail}</small></div></div>`).join('');
document.getElementById('developmentList').innerHTML = developments.map(d=>`<article class="development-row"><span class="topic">${d.topic}</span><div><h3>${d.title}</h3><p>${d.text}</p></div><span class="verified">● ${d.state}</span><span class="score">${d.score}</span></article>`).join('');
document.getElementById('pipelineBoard').innerHTML = Object.entries(pipeline).map(([stage,items])=>`<section class="pipe-column"><h3>${stage}<span>${items.length}</span></h3>${items.map(i=>`<article class="pipe-card"><strong>${i.name}</strong><p>${i.note}</p><footer><span>Owner · ${i.owner}</span><span>Due ${i.due}</span></footer></article>`).join('')}</section>`).join('');
document.getElementById('eventList').innerHTML = eventData.map(e=>`<article class="event-large"><div class="event-date"><b>${e.day}</b><span>${e.month}</span></div><div><h3>${e.name}</h3><p>${e.detail}</p><small>${e.priority} →</small></div></article>`).join('');
let days = ['31','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','1','2','3','4'];
document.getElementById('calendarDays').innerHTML = days.map((d,i)=>`<span class="${i===0||i>30?'muted':''} ${['4','12','18'].includes(d)&&i<31?'has-event':''}">${d}</span>`).join('');
document.getElementById('stakeholderGrid').innerHTML = stakeholders.map(s=>`<article><span class="org-type">${s[1]}</span><h3>${s[0]}</h3><p>${s[2]}</p><small>${s[3]} →</small></article>`).join('');
document.getElementById('sourceRows').innerHTML = sources.map(s=>`<div class="source-row"><span>${s[0]}</span><span>${s[1]}</span><span>${s[2]}</span><span>${s[3]}</span></div>`).join('');

document.querySelectorAll('[data-view]').forEach(button => button.addEventListener('click', () => setView(button.dataset.view)));
document.querySelectorAll('[data-view-target]').forEach(button => button.addEventListener('click', () => setView(button.dataset.viewTarget)));
function setView(id){ document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id)); document.querySelectorAll('.nav-item').forEach(v=>v.classList.toggle('active',v.dataset.view===id)); document.querySelector('.sidebar').classList.remove('open'); window.scrollTo({top:0,behavior:'smooth'}); }
const modal = document.getElementById('modalBackdrop'); document.getElementById('newDevelopment').onclick=()=>modal.hidden=false; document.querySelector('.close-modal').onclick=()=>modal.hidden=true; modal.onclick=e=>{if(e.target===modal)modal.hidden=true}; document.querySelector('.mobile-menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');

document.getElementById('printPdf').onclick=()=>window.print();
document.getElementById('downloadPpt').onclick=async()=>{const status=document.getElementById('reportStatus');if(!window.PptxGenJS){status.textContent='PowerPoint library is still loading. Please try again in a moment.';return}const pptx=new PptxGenJS();pptx.layout='LAYOUT_WIDE';pptx.author='Fichtner';pptx.subject='Morocco Renewable Energy Intelligence';pptx.title='Morocco Renewable Energy Intelligence Brief';pptx.company='Fichtner';pptx.lang='en-US';const green='153A35',lime='D9E858',ink='16302C',muted='64716D';let slide=pptx.addSlide();slide.background={color:green};slide.addText('FICHTNER',{x:.55,y:.42,w:3,h:.35,fontFace:'Aptos Display',fontSize:18,bold:true,color:'FFFFFF',charSpacing:2});slide.addShape(pptx.ShapeType.rect,{x:11.7,y:.48,w:.55,h:.08,line:{color:lime},fill:{color:lime}});slide.addText('MOROCCO RENEWABLE ENERGY INTELLIGENCE',{x:.55,y:2.1,w:7,h:.3,fontFace:'Aptos',fontSize:10,color:'BFD8CE',charSpacing:1.3});slide.addText(document.getElementById('reportType').value,{x:.55,y:2.52,w:8,h:1.25,fontFace:'Aptos Display',fontSize:31,bold:true,color:'FFFFFF',breakLine:false});slide.addText(`${document.getElementById('reportPeriod').value} · ${document.getElementById('reportClassification').value}`,{x:.55,y:6.75,w:8,h:.25,fontFace:'Aptos',fontSize:9,color:'BFD8CE'});slide=pptx.addSlide();slide.background={color:'FFFEFA'};slide.addText('01 · EXECUTIVE SUMMARY',{x:.6,y:.5,w:4,h:.25,fontFace:'Aptos',fontSize:9,color:'4D746B',charSpacing:1});slide.addText('Signals that require a decision',{x:.6,y:.9,w:10,h:.5,fontFace:'Aptos Display',fontSize:25,bold:true,color:ink});developments.slice(0,3).forEach((d,index)=>slide.addText(d.title,{x:.85,y:1.75+index*.78,w:10.7,h:.42,fontFace:'Aptos',fontSize:15,color:'435B54',bullet:{indent:16}}));slide.addText('Evidence-led intelligence. Analyst interpretation and Fichtner action are distinct from source-confirmed facts.',{x:.6,y:6.55,w:11.5,h:.3,fontFace:'Aptos',fontSize:8,color:muted});slide=pptx.addSlide();slide.background={color:'FFFEFA'};slide.addText('02 · PRIORITY ACTIONS',{x:.6,y:.5,w:4,h:.25,fontFace:'Aptos',fontSize:9,color:'4D746B',charSpacing:1});slide.addText('Fichtner opportunity pipeline',{x:.6,y:.9,w:10,h:.5,fontFace:'Aptos Display',fontSize:25,bold:true,color:ink});developments.slice(0,3).forEach((d,index)=>{const y=1.75+index*1.4;slide.addShape(pptx.ShapeType.roundRect,{x:.6,y,w:12,h:.95,rectRadius:.08,line:{color:'DCE1D9'},fill:{color:'FFFEFA'}});slide.addText(d.state,{x:.85,y:y+.16,w:2,h:.16,fontFace:'Aptos',fontSize:7,bold:true,color:'28745F'});slide.addText(d.title,{x:.85,y:y+.38,w:9.6,h:.22,fontFace:'Aptos',fontSize:13,bold:true,color:ink});slide.addText(d.action,{x:10.6,y:y+.39,w:1.65,h:.18,fontFace:'Aptos',fontSize:8,color:'28745F',align:'right'})});status.textContent='Preparing PowerPoint download…';await pptx.writeFile({fileName:'Fichtner_Morocco_Renewable_Intelligence_Brief.pptx'});status.textContent='PowerPoint downloaded.';};
